name: Build and publish package

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string  
      version-bump:
        type: string
        required: true  
        default: 'minor'
    secrets:
      SONATYPE_TOKEN:
        required: true 
      GPG_SECRET_KEY:
        required: true 
      GPG_SECRET_KEY_ID:
        required: true 

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout
  packages: write
  pull-requests: write 

jobs:
  buildAndPublishPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gpg
        id: gpg
        run: |
          echo "${{ secrets.GPG_SECRET_KEY }}" | base64 -d | gpg --import
          gpg -K

      - id: release
        name: Create and upload release bundles
        uses: encalmo/create-new-release-action@v1.0.1
        with:
          tag-prefix: '${{ inputs.tag-prefix }}-'
          version-bump: ${{ inputs.version-bump }}
          sonatype-token: ${{ secrets.SONATYPE_TOKEN }}
          gpg-secret-key-id: ${{ secrets.GPG_SECRET_KEY_ID }}
          release-flags: '--js --native'

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.release.outputs.new-version }}
          tag_prefix: '${{ inputs.tag-prefix }}-'

      - name: Create Github Release
        if: ${{ inputs.version-bump != 'keep' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ inputs.tag-prefix }}-${{ steps.release.outputs.new-version }}'
          release_name: ${{ inputs.tag-prefix }} release ${{ steps.release.outputs.new-version }}
          draft: false
          prerelease: false 

      - name: Move version tag
        if: ${{ inputs.version-bump == 'keep' }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: '${{ inputs.tag-prefix }}-${{ steps.release.outputs.new-version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


