name: Release new package version

on:
  workflow_dispatch:
    inputs: 
      version-bump:
        type: choice
        description: 'How to bump a version?'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - keep
  # push:
  #   branches: [main]
  #   paths:
  #     - '*.scala'        

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Create and upload new release bundles
        uses: encalmo/create-new-release-action@c47e465a29af530d6ef34c7c2431a3b39d9d4b97
        with:
          tag-prefix: 'version'
          version-bump: ${{ inputs.version-bump || 'patch' }}
          release-flags: '--js --native'
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          sonatype-token: ${{ secrets.SONATYPE_TOKEN }}
          gpg-secret-key-base64: ${{ secrets.GPG_SECRET_KEY }}
          gpg-secret-key-id: ${{ secrets.GPG_SECRET_KEY_ID }}